#define MUSIC_GAME 0
#define MUSIC_GAMEOVER 1
#define MUSIC_MENU 2
#define MUSIC_BOSS 3

#define FX_EXIT_DOOR 0
#define FX_GET_KEY 1
#define FX_REWIND 2
#define FX_SHOW_KEY 3
#define FX_FORCE_FIELD 4
#define FX_DEATH 5
#define FX_JUMP 6
#define FX_STOMP_ROBOT 7
#define FX_GET_CRYSTAL 8
#define FX_GET_VORTEX 9
#define FX_BULLET 10
#define FX_ENTER_VORTEX 11
#define FX_VORTEX_FIRE 12
#define FX_BOSS_DEATH 13
