#pragma once

// Layer grandi 4 pattern
#define laySize 4
// Due layer per sprite
#define nLayers 2
// Dimensione sprite
#define sprSize laySize * nLayers

// Fixed sprite IDs
#define PLAYER_SPRITE_ID 0
#define KEY_SPRITE_ID 2
#define CRYSTAL_SPRITE_ID 3
#define DOC_SPRITE_ID 4
#define VORTEX_SPRITE_ID 5
#define BOOM_SPRITE_ID 6

// Platforms, mines, enemies and energy fields use dynamic IDs allocated at runtime

// Player patterns
#define PLAYER_PATTERN_OFFSET (u8)0
#define PLAYER_PATTERN_SIZE laySize * nLayers
#define PLAYER_PATTERN_NUM 11
#define PLAYER_PATTERN_TOTAL PLAYER_PATTERN_SIZE * PLAYER_PATTERN_NUM
#define PLAYER_PATTERN_END PLAYER_PATTERN_OFFSET + PLAYER_PATTERN_TOTAL
#define PLAYER_FRAME(x) x * PLAYER_PATTERN_SIZE + PLAYER_PATTERN_OFFSET

// Key patterns
#define KEY_PATTERN_OFFSET PLAYER_PATTERN_END
#define KEY_PATTERN_SIZE laySize
#define KEY_PATTERN_NUM 2
#define KEY_PATTERN_TOTAL KEY_PATTERN_SIZE * KEY_PATTERN_NUM
#define KEY_PATTERN_END KEY_PATTERN_OFFSET + KEY_PATTERN_TOTAL
#define KEY_FRAME(x) x * KEY_PATTERN_SIZE + KEY_PATTERN_OFFSET

// Crystal patterns
#define CRYSTAL_PATTERN_OFFSET KEY_PATTERN_END
#define CRYSTAL_PATTERN_SIZE laySize
#define CRYSTAL_PATTERN_NUM 2
#define CRYSTAL_PATTERN_TOTAL CRYSTAL_PATTERN_SIZE * CRYSTAL_PATTERN_NUM
#define CRYSTAL_PATTERN_END CRYSTAL_PATTERN_OFFSET + CRYSTAL_PATTERN_TOTAL
#define CRYSTAL_FRAME(x) x * CRYSTAL_PATTERN_SIZE + CRYSTAL_PATTERN_OFFSET

// Evil doc patterns
#define DOC_PATTERN_OFFSET CRYSTAL_PATTERN_END
#define DOC_PATTERN_SIZE laySize
#define DOC_PATTERN_NUM 4
#define DOC_PATTERN_TOTAL DOC_PATTERN_SIZE * DOC_PATTERN_NUM
#define DOC_PATTERN_END DOC_PATTERN_OFFSET + DOC_PATTERN_TOTAL
#define DOC_FRAME(x) x * DOC_PATTERN_SIZE + DOC_PATTERN_OFFSET

// Vortex patterns
#define VORTEX_PATTERN_OFFSET DOC_PATTERN_END
#define VORTEX_PATTERN_SIZE laySize
#define VORTEX_PATTERN_NUM 3
#define VORTEX_PATTERN_TOTAL VORTEX_PATTERN_SIZE * VORTEX_PATTERN_NUM
#define VORTEX_PATTERN_END VORTEX_PATTERN_OFFSET + VORTEX_PATTERN_TOTAL
#define VORTEX_FRAME(x) x * VORTEX_PATTERN_SIZE + VORTEX_PATTERN_OFFSET

// Platform pattern
#define PLATFORM_PATTERN_OFFSET VORTEX_PATTERN_END
#define PLATFORM_PATTERN_SIZE laySize
#define PLATFORM_PATTERN_NUM 1
#define PLATFORM_PATTERN_TOTAL PLATFORM_PATTERN_SIZE * PLATFORM_PATTERN_NUM
#define PLATFORM_PATTERN_END PLATFORM_PATTERN_OFFSET + PLATFORM_PATTERN_TOTAL
#define PLATFORM_FRAME(x) x * PLATFORM_PATTERN_SIZE + PLATFORM_PATTERN_OFFSET

// Mine patterns
#define MINE_PATTERN_OFFSET PLATFORM_PATTERN_END
#define MINE_PATTERN_SIZE laySize
#define MINE_PATTERN_NUM 1
#define MINE_PATTERN_TOTAL MINE_PATTERN_SIZE * MINE_PATTERN_NUM
#define MINE_PATTERN_END MINE_PATTERN_OFFSET + MINE_PATTERN_TOTAL
#define MINE_FRAME(x) x * MINE_PATTERN_SIZE + MINE_PATTERN_OFFSET

// Boom pattern
#define BOOM_PATTERN_OFFSET MINE_PATTERN_END
#define BOOM_PATTERN_SIZE laySize
#define BOOM_PATTERN_NUM 1
#define BOOM_PATTERN_TOTAL BOOM_PATTERN_SIZE * BOOM_PATTERN_NUM
#define BOOM_PATTERN_END BOOM_PATTERN_OFFSET + BOOM_PATTERN_TOTAL
#define BOOM_FRAME(x) x * BOOM_PATTERN_SIZE + BOOM_PATTERN_OFFSET

// Enemy patterns
// Each enemy type has 6 frames: 0-1 (walk left), 3-4 (walk right), 5-6 (stunned)
// There are 4 different enemy types in total
#define ENEMY_PATTERN_OFFSET BOOM_PATTERN_END
#define ENEMY_PATTERN_SIZE laySize
#define ENEMY_FRAMES_PER_TYPE 6
#define ENEMY_TYPE_PATTERN_TOTAL ENEMY_PATTERN_SIZE * ENEMY_FRAMES_PER_TYPE
#define ENEMY_NUM_TYPES 4
#define ENEMY_PATTERN_TOTAL ENEMY_TYPE_PATTERN_TOTAL * ENEMY_NUM_TYPES
#define ENEMY_PATTERN_END ENEMY_PATTERN_OFFSET + ENEMY_PATTERN_TOTAL
#define ENEMY_FRAME(type, frame) (u8)(type * ENEMY_TYPE_PATTERN_TOTAL + frame * ENEMY_PATTERN_SIZE + ENEMY_PATTERN_OFFSET)

// Energy field patterns (for Type 2 and Type 3 enemies)
// 2 frames for animation
#define ENERGYFIELD_PATTERN_OFFSET ENEMY_PATTERN_END
#define ENERGYFIELD_PATTERN_SIZE laySize
#define ENERGYFIELD_PATTERN_NUM 2
#define ENERGYFIELD_PATTERN_TOTAL ENERGYFIELD_PATTERN_SIZE * ENERGYFIELD_PATTERN_NUM
#define ENERGYFIELD_PATTERN_END ENERGYFIELD_PATTERN_OFFSET + ENERGYFIELD_PATTERN_TOTAL
#define ENERGYFIELD_FRAME(x) x * ENERGYFIELD_PATTERN_SIZE + ENERGYFIELD_PATTERN_OFFSET

// Bullet patterns (for Type 3 enemy projectiles)
// 1 frame
#define BULLET_PATTERN_OFFSET ENERGYFIELD_PATTERN_END
#define BULLET_PATTERN_SIZE laySize
#define BULLET_PATTERN_NUM 1
#define BULLET_PATTERN_TOTAL BULLET_PATTERN_SIZE * BULLET_PATTERN_NUM
#define BULLET_PATTERN_END BULLET_PATTERN_OFFSET + BULLET_PATTERN_TOTAL
#define BULLET_FRAME(x) x * BULLET_PATTERN_SIZE + BULLET_PATTERN_OFFSET
