#pragma once

// Layer grandi 4 pattern
#define laySize 4
// Due layer per sprite
#define nLayers 2
// Dimensione sprite
#define sprSize laySize * nLayers

// Per ora il player è visualizzato usando gli sprite 0 e 1
#define PLAYER_SPRITE_ID 0
#define PLAYER_PATTERN_OFFSET 0
#define PLAYER_PATTERN_SIZE laySize * nLayers
#define PLAYER_PATTERN_NUM 13
#define PLAYER_PATTERN_TOTAL PLAYER_PATTERN_SIZE * PLAYER_PATTERN_NUM
#define PLAYER_PATTERN_END PLAYER_PATTERN_OFFSET + PLAYER_PATTERN_TOTAL
#define PLAYER_FRAME(x) x * PLAYER_PATTERN_SIZE + PLAYER_PATTERN_OFFSET

// Per ora la chiave è visualizzata usando lo sprite 2
#define KEY_SPRITE_ID 2
#define KEY_PATTERN_OFFSET PLAYER_PATTERN_END
#define KEY_PATTERN_SIZE laySize
#define KEY_PATTERN_NUM 2
#define KEY_PATTERN_TOTAL KEY_PATTERN_SIZE * KEY_PATTERN_NUM
#define KEY_PATTERN_END KEY_PATTERN_OFFSET + KEY_PATTERN_TOTAL
#define KEY_FRAME(x) x * KEY_PATTERN_SIZE + KEY_PATTERN_OFFSET

#define ENEMY_SPRITE_ID 3
#define ENEMY_PATTERN_OFFSET KEY_PATTERN_END
#define ENEMY_PATTERN_SIZE laySize
#define ENEMY_PATTERN_NUM 7
#define ENEMY_PATTERN_TOTAL ENEMY_PATTERN_SIZE * ENEMY_PATTERN_NUM
#define ENEMY_PATTERN_END ENEMY_PATTERN_OFFSET + ENEMY_PATTERN_TOTAL
#define ENEMY_FRAME(x) x * ENEMY_PATTERN_SIZE + ENEMY_PATTERN_OFFSET

#define CRYSTAL_SPRITE_ID 4
#define CRYSTAL_PATTERN_OFFSET ENEMY_PATTERN_END
#define CRYSTAL_PATTERN_SIZE laySize
#define CRYSTAL_PATTERN_NUM 2
#define CRYSTAL_PATTERN_TOTAL CRYSTAL_PATTERN_SIZE * CRYSTAL_PATTERN_NUM
#define CRYSTAL_PATTERN_END CRYSTAL_PATTERN_OFFSET + CRYSTAL_PATTERN_TOTAL
#define CRYSTAL_FRAME(x) x * CRYSTAL_PATTERN_SIZE + CRYSTAL_PATTERN_OFFSET

#define PLATFORMV_SPRITE_ID 5
#define PLATFORMV_PATTERN_OFFSET CRYSTAL_PATTERN_END
#define PLATFORMV_PATTERN_SIZE laySize
#define PLATFORMV_PATTERN_NUM 1
#define PLATFORMV_PATTERN_TOTAL PLATFORMV_PATTERN_SIZE * PLATFORMV_PATTERN_NUM
#define PLATFORMV_PATTERN_END PLATFORMV_PATTERN_OFFSET + PLATFORMV_PATTERN_TOTAL
#define PLATFORMV_FRAME(x) x * PLATFORMV_PATTERN_SIZE + PLATFORMV_PATTERN_OFFSET

#define PLATFORMH_SPRITE_ID 6
#define PLATFORMH_PATTERN_OFFSET PLATFORMV_PATTERN_END
#define PLATFORMH_PATTERN_SIZE laySize
#define PLATFORMH_PATTERN_NUM 1
#define PLATFORMH_PATTERN_TOTAL PLATFORMH_PATTERN_SIZE * PLATFORMH_PATTERN_NUM
#define PLATFORMH_PATTERN_END PLATFORMH_PATTERN_OFFSET + PLATFORMH_PATTERN_TOTAL
#define PLATFORMH_FRAME(x) x * PLATFORMH_PATTERN_SIZE + PLATFORMH_PATTERN_OFFSET
